name: Pull Vanilla

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Download Behaviour & Resource Pack
      run: |
        wget https://aka.ms/behaviorpacktemplate -O behavior_pack.zip
        wget https://aka.ms/resourcepacktemplate -O resource_pack.zip

    - name: Unzip Behaviour Pack
      uses: montudor/action-zip@v1
      with:
        args: unzip -o -qq behavior_pack.zip -d "Vanilla BP"
    
    - name: Unzip Resource Pack
      uses: montudor/action-zip@v1
      with:
        args: unzip -o -qq resource_pack.zip -d "Vanilla RP"

    - name: Delete Behaviour & Resource Pack
      run: |
        rm behavior_pack.zip
        rm resource_pack.zip

    - name: Create Commit
      run: |
        git add -A .
        git config --global user.email "bot@github.com"
        git config --global user.name "Github Bot"
        git commit -m "Sync with mojang"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pr-pages

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "[Sync] Latest Behaviour Pack & Resource Pack" --body "Sync from latest aka.ms RP & BP" --head pr-pages
