name: Pull Vanilla

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Download Behaviour & Resource Pack
      run: |
        wget https://aka.ms/behaviorpacktemplate -O behavior_pack.zip
        wget https://aka.ms/resourcepacktemplate -O resource_pack.zip

    - name: Unzip Behaviour Pack
      uses: montudor/action-zip@v1
      with:
        args: unzip -o -qq behavior_pack.zip -d "Vanilla BP"
    
    - name: Unzip Resource Pack
      uses: montudor/action-zip@v1
      with:
        args: unzip -o -qq resource_pack.zip -d "Vanilla RP"

    - name: Delete Behaviour & Resource Pack
      run: |
        rm behavior_pack.zip
        rm resource_pack.zip

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: '[Sync] Sync with mojang',
            owner,
            repo,
            head: '${{ github.ref_name }}',
            base: 'develop',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: result.data.number,
            labels: ['feature', 'automated pr']
          });
